#!/bin/bash
if [[ $EUID -ne 0 ]]; then
        echo "This script must be run as root"
        exit 1
fi

binary_url="${1}"
tmp="$(mktemp)"

export HTTPS_PROXY=http://webproxy-nais.nav.no:8088
if ! curl --fail -kL "$binary_url" > "$tmp"; then
        echo "Downloading binary failed"
        exit 1
fi
unset HTTPS_PROXY

systemctl stop herlighet
mv "$tmp" /usr/local/bin/herlighet
chmod +x /usr/local/bin/herlighet
systemctl start herlighet

echo "Successfully created new hole"
