herlighetprod:
  hosts:
    prod-pg.intern.nav.no:
    prod-pg-backup.intern.nav.no:

herlighetdev:
  hosts:
    dev-pg.intern.nav.no:
    dev-pg-backup.intern.nav.no:

gateways:
  children:
    herlighetdev:
    herlighetprod:
