name: Build, push, and deploy

on: [push]

env:
  docker_image: docker.pkg.github.com/${{ github.repository }}/herlighet:${{ github.sha }}

jobs:

  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: build binary
        run: |
          go get . && go build .
      - name: create release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1.0.1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - name: upload apiserver binary
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./herlighet
          asset_name: herlighet
          asset_content_type: application/octet-stream
